steps:
  # build the container image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - "--destination=gcr.io/$PROJECT_ID/image"
      - "--cache=true"
      - "--cache-ttl=96h"

  # run tests
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["run", "--rm", "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA", "npm", "test"]

  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
      - "--region"
      - "europe-north1"
      - "--platform"
      - "managed"
images:
  - "gcr.io/$PROJECT_ID/backend:$COMMIT_SHA"
